const assert = require('node:assert/strict');
const { DEFAULTS, normalize, createPlan, totalSeconds, formatTime, upcomingWork } = require('../timer-core.js');
const p = createPlan(DEFAULTS);
assert.equal(p.length, 1 + 3 * (5 + 4 + 1));
assert.equal(totalSeconds(p), 1080);
assert.equal(formatTime(totalSeconds(p)), '18:00');
assert.equal(p[0].kind, 'warmup');
assert.equal(p[1].title, 'Jump Squats');
assert.equal(p.at(-2).title, 'Burpee mit Tuck Jump');
assert.equal(p.at(-1).kind, 'roundRest');
assert.equal(p.at(-1).round, 3);
assert.equal(p.filter(x => x.kind === 'work').length, 15);
assert.equal(p.filter(x => x.kind === 'roundRest').length, 3);
assert.equal(upcomingWork(p, 1).title, 'Plank Walk');
assert.equal(formatTime(61.3), '01:02');
const custom = createPlan({ warmup: 0, work: 30, rest: 0, roundRest: 0, rounds: 1, exercises: ['Sprint'] });
assert.equal(totalSeconds(custom), 30);
assert.equal(custom.length, 1);
assert.deepEqual(normalize({ rounds: 99, work: -1, exercises: ['  ', 'Test'] }).exercises, ['Test']);
assert.equal(normalize({ rounds: 99 }).rounds, 20);
assert.equal(normalize({ work: -1 }).work, 5);
console.log('PASS: Standard-Workout 18:00 inkl. finaler Rundenpause, Phasen, Sonderfälle, Normalisierung');
